<?php

namespace App\Services;

use App\Models\Kartu;
use App\Models\KartuAccessLog;
use App\Models\User;
use App\Repositories\KartuAccessLogRepository;
use App\Repositories\KartuRepository;
use Illuminate\Support\Carbon;
use Illuminate\Validation\ValidationException;

class KartuService
{
    protected KartuRepository $kartuRepository;
    protected KartuAccessLogRepository $accessLogRepository;

    public function __construct(
        KartuRepository $kartuRepository,
        KartuAccessLogRepository $accessLogRepository
    ) {
        $this->kartuRepository     = $kartuRepository;
        $this->accessLogRepository = $accessLogRepository;
    }

    /**
     * Paginated, filterable list of cards.
     *
     * @param  array<string, mixed>  $filters
     * @param  int  $perPage
     * @param  bool  $includeDeleted  Include soft-deleted cards (is_deleted = true)
     */
    public function list(array $filters = [], int $perPage = 15, bool $includeDeleted = false)
    {
        // Sinkronisasi status realtime: setiap kali daftar kartu diminta,
        // pastikan status kartu mengikuti masa berlaku efektif pada jam
        // terkini — kartu yang sudah lewat (valid_until + grace) diturunkan
        // ke Non Aktif, sementara kartu Non Aktif yang masa berlakunya
        // diperpanjang (mis. admin menambah tenggang / valid_until) kembali
        // diangkat menjadi Aktif. Ini melengkapi scheduler hourly agar UI
        // selalu akurat tanpa menunggu cron berikutnya atau tap gate.
        try {
            $this->deactivateExpired();
            $this->reactivateWithinValidity();
        } catch (\Throwable $e) {
            // Jangan gagalkan permintaan list hanya karena sinkronisasi
            // status gagal; cukup lewatkan agar data tetap bisa ditampilkan.
        }

        return $this->kartuRepository->filter($filters, $perPage, $includeDeleted);
    }

    /**
     * Get a single card (with owner) by id.
     *
     * @return \App\Models\Kartu
     */
    public function find($id)
    {
        return $this->kartuRepository->findOrFail($id)->load('user');
    }

    /**
     * Create a new card.
     *
     * @return \App\Models\Kartu
     */
    public function create(array $data)
    {
        // Satu Kartu Keluarga (KK) hanya boleh memiliki maksimal 4 kartu akses.
        $this->assertKkCardLimit($data['user_id']);

        // The card number (UID) is generated by the system so the admin does
        // not need to type / tap a physical card while registering.
        if (empty($data['card_number'])) {
            $data['card_number'] = $this->generateCardNumber();
        }

        // The RFID tag (physical UID) is generated by the system for now.
        if (empty($data['rfid_tag'])) {
            $data['rfid_tag'] = $this->generateRfidTag();
        }

        $kartu = $this->kartuRepository->create($data)->load('user');

        // Capture and persist the current access decision
        $decision = $kartu->evaluateAccess();
        $kartu->update([
            'access_allowed' => (bool) ($decision['allowed'] ?? false),
            'access_reason'  => $decision['reason'] ?? null,
            'access_message' => $decision['message'] ?? null,
            'access_at'      => Carbon::now(),
        ]);

        return $kartu->refresh();
    }

    /**
     * Get remaining card slots for a user (considering KK group).
     */
    public function getRemainingSlots($userId): int
    {
        $user = User::find($userId);
        if ($user === null) {
            return Kartu::MAX_CARDS_PER_KK;
        }

        $userIds = ! empty($user->no_kk)
            ? User::where('no_kk', $user->no_kk)->pluck('id')->all()
            : [$user->id];

        $count = $this->kartuRepository->countActiveForUsers($userIds);

        return max(0, Kartu::MAX_CARDS_PER_KK - $count);
    }

    /**
     * Create multiple cards at once, each with a different RFID tag.
     * All cards share the same base data (user_id, nama, status, etc.).
     *
     * @param  array   $baseData  Fields shared across all cards (no rfid_tag).
     * @param  array   $rfidTags  RFID UIDs to assign, one per card.
     * @return array<\App\Models\Kartu>
     */
    public function createBatch(array $baseData, array $rfidTags): array
    {
        $remaining = $this->getRemainingSlots($baseData['user_id']);

        if (count($rfidTags) > $remaining) {
            throw ValidationException::withMessages([
                'rfid_tags' => [
                    $remaining === 0
                        ? 'KK ini sudah mencapai batas maksimal ' . Kartu::MAX_CARDS_PER_KK . ' kartu akses.'
                        : "Hanya tersisa {$remaining} slot kartu untuk KK ini, tidak bisa menambah " . count($rfidTags) . ' kartu sekaligus.',
                ],
            ]);
        }

        $created = [];
        foreach ($rfidTags as $rfidTag) {
            $data            = $baseData;
            $data['rfid_tag'] = $rfidTag;
            // card_number is generated inside create() when empty.
            $created[] = $this->create($data);
        }

        return $created;
    }

    /**
     * Ensure that assigning a card to the given user does not exceed the
     * maximum number of access cards allowed per Kartu Keluarga (no_kk).
     *
     * Cards are counted across every user that shares the same no_kk. When a
     * user has no no_kk, only their own cards are counted.
     *
     * @throws \Illuminate\Validation\ValidationException
     */
    protected function assertKkCardLimit($userId, $ignoreKartuId = null): void
    {
        $user = User::find($userId);

        if ($user === null) {
            return;
        }

        $userIds = ! empty($user->no_kk)
            ? User::where('no_kk', $user->no_kk)->pluck('id')->all()
            : [$user->id];

        $count = $this->kartuRepository->countActiveForUsers($userIds, $ignoreKartuId);

        if ($count >= Kartu::MAX_CARDS_PER_KK) {
            throw ValidationException::withMessages([
                'user_id' => [
                    'Satu Kartu Keluarga (KK) hanya boleh memiliki maksimal '
                        . Kartu::MAX_CARDS_PER_KK . ' kartu akses.',
                ],
            ]);
        }
    }

    /**
     * Generate a unique system card number / UID (e.g. "KRT-00042317").
     */
    protected function generateCardNumber(): string
    {
        do {
            $number = 'KRT-' . str_pad((string) random_int(0, 99999999), 8, '0', STR_PAD_LEFT);
        } while ($this->kartuRepository->findByCardNumber($number) !== null);

        return $number;
    }

    /**
     * Generate a unique system RFID tag / physical UID (hex, e.g. "A1B2C3D4E5").
     */
    protected function generateRfidTag(): string
    {
        do {
            $tag = strtoupper(bin2hex(random_bytes(5)));
        } while ($this->kartuRepository->findByRfidTag($tag) !== null);

        return $tag;
    }

    /**
     * Update an existing card.
     *
     * @return \App\Models\Kartu
     */
    public function update($id, array $data)
    {
        // Bila kartu dipindahkan ke user lain, tetap patuhi batas 4 kartu per KK.
        if (! empty($data['user_id'])) {
            $this->assertKkCardLimit($data['user_id'], $id);
        }

        $kartu = $this->kartuRepository->update($id, $data)->load('user');

        // Refresh access snapshot when card is updated
        $decision = $kartu->evaluateAccess();
        $kartu->update([
            'access_allowed' => (bool) ($decision['allowed'] ?? false),
            'access_reason'  => $decision['reason'] ?? null,
            'access_message' => $decision['message'] ?? null,
            'access_at'      => Carbon::now(),
        ]);

        return $kartu->refresh();
    }

    /**
     * Delete a card.
     */
    public function delete($id): bool
    {
        return $this->kartuRepository->delete($id);
    }

    /*
    |--------------------------------------------------------------------------
    | Gate access (tab-in / tab-out)
    |--------------------------------------------------------------------------
    */

    /**
     * Handle a tab-in (entry) tap.
     */
    public function tabIn(string $cardNumber, array $context = []): array
    {
        return $this->processTap($cardNumber, KartuAccessLog::DIRECTION_IN, $context);
    }

    /**
     * Handle a tab-out (exit) tap.
     */
    public function tabOut(string $cardNumber, array $context = []): array
    {
        return $this->processTap($cardNumber, KartuAccessLog::DIRECTION_OUT, $context);
    }

    /**
     * Evaluate a card tap, log it, and return the gate decision.
     *
     * @return array<string, mixed>
     */
    public function processTap(string $cardNumber, int $direction, array $context = []): array
    {
        $kartu = $this->kartuRepository->findByCardNumber($cardNumber);

        if ($kartu === null) {
            $decision = [
                'allowed' => false,
                'reason'  => Kartu::REASON_UNKNOWN_CARD,
                'message' => Kartu::REASON_MESSAGES[Kartu::REASON_UNKNOWN_CARD],
            ];
        } else {
            $decision = $kartu->evaluateAccess();
            // Persist this access decision so the UI always shows the latest gate verdict
            $kartu->update([
                'access_allowed' => (bool) ($decision['allowed'] ?? false),
                'access_reason'  => $decision['reason'] ?? null,
                'access_message' => $decision['message'] ?? null,
                'access_at'      => Carbon::now(),
            ]);
        }

        $log = $this->accessLogRepository->create([
            'kartu_id'       => $kartu ? $kartu->id : null,
            'user_id'        => $kartu ? $kartu->user_id : null,
            'card_number'    => $cardNumber,
            'no_plat'        => $context['no_plat'] ?? null,
            'direction'      => $direction,
            'access_granted' => $decision['allowed'],
            'reason'         => $decision['reason'],
            'gate'           => $context['gate'] ?? null,
            'tapped_at'      => Carbon::now('Asia/Jakarta'),
        ]);

        return [
            'access_granted'  => $decision['allowed'],
            'reason'          => $decision['reason'],
            'message'         => $decision['message'],
            'direction'       => $direction,
            'direction_label' => KartuAccessLog::DIRECTIONS[$direction] ?? null,
            'card_number'     => $cardNumber,
            'no_plat'         => $context['no_plat'] ?? null,
            'kartu'           => $kartu,
            'log_id'          => $log->id,
            'tapped_at'       => $log->tapped_at,
        ];
    }

    /**
     * Get the current access status of a card by its number (no logging).
     *
     * @return array<string, mixed>
     */
    public function checkStatus(string $cardNumber): array
    {
        $kartu = $this->kartuRepository->findByCardNumber($cardNumber);

        if ($kartu === null) {
            return [
                'found'       => false,
                'card_number' => $cardNumber,
                'access'      => [
                    'allowed' => false,
                    'reason'  => Kartu::REASON_UNKNOWN_CARD,
                    'message' => Kartu::REASON_MESSAGES[Kartu::REASON_UNKNOWN_CARD],
                ],
            ];
        }

        return $this->statusPayload($kartu) + ['found' => true];
    }

    /**
     * Get the current access status of a card by id.
     *
     * @return array<string, mixed>
     */
    public function statusById($id): array
    {
        $kartu = $this->kartuRepository->findOrFail($id)->load('user');

        return $this->statusPayload($kartu) + ['found' => true];
    }

    /**
     * Build a status payload with computed validity flags.
     *
     * @return array<string, mixed>
     */
    protected function statusPayload(Kartu $kartu): array
    {
        $graceUntil = $kartu->graceUntil();

        return [
            'kartu'         => $kartu,
            'is_active'     => $kartu->isActive(),
            'is_blacklisted' => $kartu->isBlacklisted(),
            'has_outstanding' => $kartu->hasOutstanding(),
            'is_not_yet_valid' => $kartu->isNotYetValid(),
            'is_expired'    => $kartu->isExpired(),
            'in_grace_period' => $kartu->isInGracePeriod(),
            'grace_until'   => $graceUntil ? $graceUntil->toDateTimeString() : null,
            'access'        => $kartu->evaluateAccess(),
        ];
    }

    /**
     * Blacklist a card (e.g. because of unpaid dues).
     *
     * @return \App\Models\Kartu
     */
    public function blacklist($id, ?string $reason = null)
    {
        $kartu = $this->kartuRepository->update($id, [
            'status'           => Kartu::STATUS_BLACKLIST,
            'is_blacklisted'   => true,
            'blacklist_reason' => $reason,
        ])->load('user');

        // Refresh access snapshot when blacklisting
        $decision = $kartu->evaluateAccess();
        $kartu->update([
            'access_allowed' => (bool) ($decision['allowed'] ?? false),
            'access_reason'  => $decision['reason'] ?? null,
            'access_message' => $decision['message'] ?? null,
            'access_at'      => Carbon::now(),
        ]);

        return $kartu->refresh();
    }

    /**
     * Remove a card from the blacklist and reactivate it.
     *
     * @return \App\Models\Kartu
     */
    public function clearBlacklist($id)
    {
        $kartu = $this->kartuRepository->update($id, [
            'status'           => Kartu::STATUS_AKTIF,
            'is_blacklisted'   => false,
            'blacklist_reason' => null,
        ])->load('user');

        // Refresh access snapshot when clearing blacklist
        $decision = $kartu->evaluateAccess();
        $kartu->update([
            'access_allowed' => (bool) ($decision['allowed'] ?? false),
            'access_reason'  => $decision['reason'] ?? null,
            'access_message' => $decision['message'] ?? null,
            'access_at'      => Carbon::now(),
        ]);

        return $kartu->refresh();
    }

    /**
     * Paginated access logs for a given card.
     */
    public function logs($kartuId, int $perPage = 15)
    {
        return $this->accessLogRepository->filter(['kartu_id' => $kartuId], $perPage);
    }

    /**
     * Paginated access logs across all cards (most recent first).
     *
     * Used by the gate console so the tap history survives a page reload.
     */
    public function recentLogs(array $filters = [], int $perPage = 15)
    {
        return $this->accessLogRepository->filter($filters, $perPage);
    }

    /**
     * Automatically set every active card whose validity (including its grace
     * period) has fully passed to "Non Aktif".
     *
     * Intended to be triggered by a scheduled task so cards get deactivated
     * even when they are never tapped again.
     *
     * @return int Number of cards that were deactivated.
     */
    public function deactivateExpired(): int
    {
        $deactivated = 0;

        foreach ($this->kartuRepository->activeExpiredCandidates() as $kartu) {
            if ($kartu->deactivateIfExpired()) {
                $deactivated++;
            }
        }

        return $deactivated;
    }

    /**
     * Automatically restore every Non Aktif card back to "Aktif" when its
     * validity window (including the grace period) still covers the current
     * moment. Blacklisted cards and cards without a validity window are
     * intentionally left untouched so manual overrides remain sticky.
     *
     * @return int Number of cards that were reactivated.
     */
    public function reactivateWithinValidity(): int
    {
        $reactivated = 0;

        foreach ($this->kartuRepository->inactiveWithinValidityCandidates() as $kartu) {
            if ($kartu->reactivateIfWithinValidity()) {
                $reactivated++;
            }
        }

        return $reactivated;
    }

    /**
     * Automatically blacklist cards with outstanding payments that exceed
     * the grace period + 1 day.
     *
     * Intended to be triggered by a scheduled task (daily) so cards are
     * blacklisted automatically even when they are never tapped.
     *
     * @return int Number of cards that were blacklisted.
     */
    public function blacklistOverdue(): int
    {
        $blacklisted = 0;

        $kandidat = Kartu::where('status', Kartu::STATUS_AKTIF)
            ->where('is_blacklisted', false)
            ->with('user')
            ->get();

        foreach ($kandidat as $kartu) {
            if ($kartu->blacklistIfOutstandingPastDue()) {
                $blacklisted++;
            }
        }

        return $blacklisted;
    }
}
